//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outage {
    using System;
    using Outage;
    
    
    /// Generic user of energy - a  point of consumption on the power system model. This class is extended with the category attribute in order to support different load types, e.g. streetlights.
    public class EnergyConsumer : ConductingEquipment {
    }
}
