//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outage {
    using System;
    using Outage;
    
    
    /// An electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called "connectivity nodes".
    public class Terminal : IdentifiedObject {
    }
}
