// <auto-generated />
namespace OutageDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fields_in_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fields_in_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202002180650507_fields_in_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
