//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Outage
{
    using System;
    
    
    public enum AnalogSignalType {
        
        /// A meter remotely accessed through AMI, used for average measurement on consumers (ServicePoint). Same semantics as MeasuredValue (type=Voltage...VoltageAngle).
        BellwetherMeter,
        
        /// Bandwidth of a regulating control. The type must be the same as in the corresponding ControlSetValue signal (type=Voltage..CosPhi).
        ControlBandwidth,
        
        /// Initial delay of a regulating control or relay stage (type=Time)
        ControlDelay,
        
        /// High value of a ControlLimit (type=MER_V..MER_VANGLE, Analog).
        ControlLimitHigh,
        
        /// Low value of a ControlLimit (type=Voltage...VoltageAngle).
        ControlLimitLow,
        
        /// Set point (target) of a RegulatingControl or RelayStage. The measurement type is determined by ControlSettings.measurementType or RelayCatalog.measurementType.
        ControlSetValue,
        
        /// RegulatingControl.imagSlope (type=Unitless).
        ControlSlopeImag,
        
        /// RegulatingControl.realSlope (type=Unitless).
        ControlSlopeReal,
        
        /// Subsequent delay of  a regulating control (type=Time)
        ControlSubDelay,
        
        /// A custom type (none of the DMS recognized types)
        Custom,
        
        /// Recorded value of fault current or voltage (type=Voltage or Current).
        FaultRecorder,
        
        /// Analog measured value (type=Voltage...VoltageAngle, RelativeVoltage).
        MeasuredValue,
        
        /// Reclosing delay of a reclosing relay stage (type=Time)
        RecloseDelay,
        
        /// Refreshes the value of a RegulatingControl setting
        Refresh,
        
        /// Weather measurement. Must be associated with a WeatherRegion(type=Temperature, Humidity, WindSpeed, FeelsLike, SunchineMinutes, SkyCover, Insolation).
        WeatherData,
    }
}
