//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Outage
{
    using System;
    using DataModel.Outage;
    
    
    /// The parts of a power system that are physical devices, electronic or mechanical
    public class Equipment : PowerSystemResource {
    }
}
