//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Outage
{
    using System;
    using DataModel.Outage;
    
    
    /// A winding is associated with each defined terminal of a transformer (or phase shifter).
    public class TransformerWinding : ConductingEquipment {
        
        /// A transformer has windings
        private PowerTransformer cim_PowerTransformer;
        
        private const bool isPowerTransformerMandatory = true;
        
        private const string _PowerTransformerPrefix = "cim";
        
        public virtual PowerTransformer PowerTransformer {
            get {
                return this.cim_PowerTransformer;
            }
            set {
                this.cim_PowerTransformer = value;
            }
        }
        
        public virtual bool PowerTransformerHasValue {
            get {
                return this.cim_PowerTransformer != null;
            }
        }
        
        public static bool IsPowerTransformerMandatory {
            get {
                return isPowerTransformerMandatory;
            }
        }
        
        public static string PowerTransformerPrefix {
            get {
                return _PowerTransformerPrefix;
            }
        }
    }
}
