name: OMS Angular 

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x 
    
    - name: Install dependencies
      run: |
        cd ./OMS-Angular
        npm i
    
    - name: Build Angular application for production
      run: |
        cd ./OMS-Angular
        npm run build --prod
      env:
        CI: true
